name: Docker

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define the jobs
jobs:
  # Build and push the Docker image
  docker:
    # Run the job on ubuntu-latest
    runs-on: ubuntu-latest
    # Steps of the job
    steps:
      # Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          # Use your Docker Hub username and password as secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          # Use the same tag as in step 3
          push: true
          tags: <dockkerhubaccount>/CA3:latest
